-- Non-plugins configs
require "user.options"
require "user.keymaps"
require "user.autocommands"

-- Plugin configs
require "user.plugins"
require "user.colorscheme"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.trouble"
require "user.neoscroll"
require "user.colorizer"
require "user.cmp"
require "user.mason"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.gitsigns"
require "user.tailwindcss"
